create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_id uuid,
  created_at timestamptz not null default now(),
  unique (endpoint)
);

alter table push_subscriptions enable row level security;

-- Allow anyone to insert (we control auth via API secret)
create policy "allow_insert" on push_subscriptions for insert with check (true);

-- Allow anyone to delete their own subscription by endpoint
create policy "allow_delete" on push_subscriptions for delete using (true);

-- Allow service role full access
create policy "service_full_access" on push_subscriptions for all using (true) with check (true);
